[pytest]

python_files = test_*.py *_test.py
python_classes = Test* *Test
python_functions = test_*

markers =
    smoke: быстрая проверка критичной функциональности
    regression: полное тестирование после изменений
    negative: негативные сценарии
    contract: валидация структуры ответа (Contract Testing)
    parametrize: тесты с множественными наборами данных


testpaths = tests

filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning

addopts =
    -v
    --strict-markers
    --tb=short

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %H:%M:%S
